### ISSUE TITLE
GuildWar Script not going back to the main menu after raid

### ISSUE THREAD

**Issue by Rimewind** [Frizz925/gbf-autopilot-core#13]
After the bot runs and beats extreme +, when it goes to the "quest results" page, it stops working and doesn't continue to loop.

this is what it says for me:
[0] 2018-02-14T19:24:30.918Z - info: Started listening on localhost:49544
[0] 2018-02-14T19:24:35.193Z - debug: Client '2NAz8aoLogBHN0a3AAAA' connected!
[0] 2018-02-14T19:24:35.625Z - debug: Socket '2NAz8aoLogBHN0a3AAAA' started
[0] 2018-02-14T19:24:36.109Z - debug: Running scenario 'GuildWar'
[0] 2018-02-14T19:26:06.386Z - error:  Error: Action element({"selector":".btn-result,.btn-usual-ok,.btn-usual-cancel,.btn-usual-close,#cjs-lp-rankup,.btn-control","scroll":false,"retry":true}) timed out after 60000ms!
[0]     at cb (C:\Users\Justin\Desktop\gbf-autopilot-dangerous\server\dist\server.js:321:22)
[0]     at Timeout._onTimeout (C:\Users\Justin\Desktop\gbf-autopilot-dangerous\server\dist\server.js:323:13)
[0]     at ontimeout (timers.js:386:11)
[0]     at tryOnTimeout (timers.js:250:5)
[0]     at Timer.listOnTimeout (timers.js:214:5)
[0] 2018-02-14T19:26:55.182Z - debug: Got stop request from socket '2NAz8aoLogBHN0a3AAAA'
[0] 2018-02-14T19:26:55.186Z - debug: Stopping socket '2NAz8aoLogBHN0a3AAAA'

**Comment by pannatatm** [comment]
If you're using Automatic End Raid/Quest in Vitamate try turning it off.

**Comment by Frizz925** [comment]
Incomplete bug report. Closing.

**Comment by Frizz925** [comment]
Please check the [bug reporting](https://github.com/Frizz925/gbf-autopilot/wiki/Bug-Reporting) wiki page before submitting a bug issue to cause less headache for the developers to fix the bug. Also you seem to run earlier version of the bot before the rewrite which is no longer maintained and makes this bug report no longer valid.
