### ISSUE TITLE
lua script problem(can' use skill or attack)

### ISSUE THREAD

**Issue by cccwzi** [Frizz925/gbf-autopilot-core#18]
### Summary
Sorry about here's an error occurred.

The event mode can't run properly.It will stop in the battle and do nothing until the error occurred.

Thank you for your helping indeed.
### Branch
master

### Commit hash
c4e600a7bdce061883979bffc6f400b2a067fe2f

### Expected results
Use skills and attack 

### Actual results
Do nothing and get error

### System information
OS: Windows 10 Pro 64-bit
Screen resolution: 2560x1440 @ 1.0x
Chrome version: 64.0.3282.186 (Official Build) (64-bit)
Node.js version: v8.9.4
Python version: 3.5.2

### Configuration
```
[Server]
ListenerPort=49544
ProcessTimeoutInMs=60000
WorkerTimeoutInMs=500
WaitAjaxTimeoutInMs=5000
JsonRpcEndpoint=/jsonrpc


[Controller]
ListenerPort=49545
MouseTween=easeInOutCubic

[Debug]
LogLevel=debug
LogToFile=false
LogToOutput=true
LogToFileDirectory=log
LogSocket=false
ThrowErrors=false
TrialBattleMode=false

[General]
Language=en
MaxNumActionRetries=3
MinWaitTimeInMsAfterRefresh=2000
TimeLimitInSeconds=3600
UseViramate=true
MaxNumPotionsToUse=999
UseFullElixirsWhenNoRemainingHalfAPPotions=false
UseFullElixirsFirst=false
Treasure=
TreasureTarget=

[Inputs]
DelayInMsBetweenMouseDownAndUp=40
RandomDelayInMsBetweenMouseDownAndUp=20
MouseSpeed=580
MouseSpeedBase=150
MouseScrollSpeed=250
ExitKeyCode=112
WaitTimeInMsBeforeClickInput=50

[PartySelection]
PreferredPartyGroup=3
PreferredPartyDeck=2
PreferredPartySet=A
PreferredNightmareModePartyGroup=2
PreferredNightmareModePartyDeck=1
PreferredNightmareModePartySet=A

[Summons]
OnlyRerollSummonsEnabled=false
PreferredSummons=Kaguya
DefaultSummonAttributeTab=Misc
RerollSummonWhenNoPreferredSummonWasFound=false

[Combat]
MinWaitTimeInMsAfterAttack=500
MinWaitTimeInMsAfterSummon=3000
MinWaitTimeInMsAfterAbility=2200
LuaScript=scripts/at.lua

[PokerMode]
Enabled=false
ChipAmount=1000
WinningRoundCap=5
WinningChipsCap=16000
WinningRateBase=0.75
WinningRateModifier=0.08

[EventMode]
Enabled=true
EventRaidUrl="http://game.granbluefantasy.jp/#quest/supporter/510031/5"
EventRaidScript=scripts/at.lua
NightmareModeUrl="http://game.granbluefantasy.jp/#quest/supporter/510031/5"
NightmareModeScript=scripts/at.lua
EventPageUrl="http://game.granbluefantasy.jp/#quest/extra"
NightmareModePreferredSummons=
NightmareModeSummonAttributeTab=
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=false
NightmareModeAvailableAtStart=false
WaitTimeInMsAfterEventPageIsLoaded=1000

[EventTreasureMode]
Enabled=false
EventTreasureUrl=
EventTreasureSoloUrl=
EventTreasureSoloModeScript=
EventTreasureRaidUrl=
EventTreasureRaidModeScript=
EventTreasureRaidItemRequiredCount=
NightmareModeUrl=
NightmareModeScript=
NightmareModePreferredSummons=
NightmareModeSummonAttributeTab=
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
NightmareModeAvailableAtStart=false

[RiseOfTheBeastsMode]
Enabled=false
RiseOfTheBeastsUrl=
RiseOfTheBeastsLuaScript=

[CoopSoloMode]
Enabled=false
LuaScript=

[CoopGuestMode]
Enabled=false
LuaScript=

[CustomizedScheduling]
Enabled=false
SchedulingLuaScript=

[DimensionalHalo]
RetreatWhenNoDimensionalHaloTransformation=true
```
### Extension.js
```
module.exports = ["gbf-autopilot-core"];
module.exports = ["gbf-autopilot-poker"];
```
### Lua Script
```
character_4:UseSkill(2)
Attack()
```
### log
```
> gbf-autopilot@0.0.1 start D:\WEB\gbf\gbf-autopilot
> cross-env NODE_ENV=production concurrently "node index.js" "python server.py"

[1]  * Running on http://localhost:49545/ (Press CTRL+C to quit)
[0] 2018-03-07T12:58:40.548Z - debug: Started listening on localhost:49544
[0] 2018-03-07T12:58:40.722Z - debug: Client 'TJQUGL_Dg6psBelWAAAA' connected!
[0] 2018-03-07T12:58:41.695Z - debug: Socket 'TJQUGL_Dg6psBelWAAAA' started
[1] 127.0.0.1 - - [07/Mar/2018 20:58:41] "POST / HTTP/1.1" 200 -
[0] 2018-03-07T12:58:41.710Z - info: Autopilot started.
[0] 2018-03-07T12:58:41.712Z - info: Using 'Event' mode.
[0] 2018-03-07T12:58:41.722Z - debug: Location change: http://game.granbluefantasy.jp/#quest/extra
[0] 2018-03-07T12:58:42.736Z - debug: Waiting element: .atx-lead-link
[0] 2018-03-07T12:58:42.748Z - debug: Checking element: .ico-difficulty-5,.ico-difficulty-8
[0] 2018-03-07T12:58:42.941Z - info: Using quest page: http://game.granbluefantasy.jp/#quest/supporter/510031/5
[0] 2018-03-07T12:58:42.956Z - debug: Ajax: GET /quest/user_action_point
[0] 2018-03-07T12:58:43.223Z - debug: Ajax: GET /quest/quest_data/510031/5
[0] 2018-03-07T12:58:43.555Z - debug: Ajax: POST /quest/set_return_point
[0] 2018-03-07T12:58:43.669Z - debug: Location change: http://game.granbluefantasy.jp/#quest/supporter/510031/5
[0] 2018-03-07T12:58:44.695Z - debug: Waiting element: .atx-lead-link
[0] 2018-03-07T12:58:44.703Z - debug: Checking element: .icon-supporter-type-7.unselected
[0] 2018-03-07T12:58:44.707Z - debug: Timeout: 50
[0] 2018-03-07T12:58:44.758Z - debug: Preferred summons: 0=Kaguya
[0] 2018-03-07T12:58:44.923Z - info: Selected summon: Kaguya
[0] 2018-03-07T12:58:44.924Z - debug: Timeout: 50
[0] 2018-03-07T12:58:44.976Z - debug: Waiting element: .pop-deck.supporter,.pop-deck.supporter_raid
[1] 127.0.0.1 - - [07/Mar/2018 20:58:45] "POST / HTTP/1.1" 200 -
[0] 2018-03-07T12:58:45.470Z - debug: Timeout: 4000
[0] 2018-03-07T12:58:46.050Z - debug: Timeout: 500
[0] 2018-03-07T12:58:46.550Z - debug: Using party set: A
[0] 2018-03-07T12:58:46.553Z - debug: Clicking with condition: .btn-deck-group
[0] 2018-03-07T12:58:46.555Z - debug: Checking element: .btn-deck-group.type-groupA
[0] 2018-03-07T12:58:46.566Z - debug: Using party group: 3
[0] 2018-03-07T12:58:46.567Z - debug: Clicking with condition: .btn-select-group.id-3
[0] 2018-03-07T12:58:46.568Z - debug: Checking element: .btn-select-group.id-3.selected
[0] 2018-03-07T12:58:46.579Z - debug: Timeout: 500
[0] 2018-03-07T12:58:47.081Z - debug: Using party deck: 2
[0] 2018-03-07T12:58:47.082Z - debug: Clicking with condition: .prt-deck-slider li:nth-child(2) > a
[0] 2018-03-07T12:58:47.082Z - debug: Checking element: .prt-deck-slider li:nth-child(2) > a.flex-active
[0] 2018-03-07T12:58:47.094Z - debug: Starting battle...
[0] 2018-03-07T12:58:47.094Z - debug: Clicking with condition: .btn-usual-ok
[0] 2018-03-07T12:58:47.098Z - debug: Clicking element: .btn-usual-ok
[1] 127.0.0.1 - - [07/Mar/2018 20:58:47] "POST / HTTP/1.1" 200 -
[0] 2018-03-07T12:58:47.592Z - debug: Timeout: 750
[0] 2018-03-07T12:58:48.344Z - debug: Clicking element: .btn-usual-ok
[1] 127.0.0.1 - - [07/Mar/2018 20:58:48] "POST / HTTP/1.1" 200 -
[0] 2018-03-07T12:58:48.832Z - debug: Timeout: 750
[0] 2018-03-07T12:58:49.582Z - debug: Clicking element: .btn-usual-ok
[1] 127.0.0.1 - - [07/Mar/2018 20:58:50] "POST / HTTP/1.1" 200 -
[0] 2018-03-07T12:58:50.132Z - debug: Timeout: 750
[0] 2018-03-07T12:58:50.883Z - debug: Clicking element: .btn-usual-ok
[1] 127.0.0.1 - - [07/Mar/2018 20:58:51] "POST / HTTP/1.1" 200 -
[0] 2018-03-07T12:58:51.379Z - debug: Timeout: 750
[0] 2018-03-07T12:58:51.984Z - debug: Waiting element: .btn-attack-start.display-on,.btn-result,.cnt-result
[0] 2018-03-07T12:58:58.231Z - debug: Viramate: type=getCombatState
[0] 2018-03-07T12:59:58.235Z - info: AP potion used: 0
[0] 2018-03-07T12:59:58.236Z - error:  Error: Action viramate({"type":"getCombatState"}) timed out after 60000ms!
[0]     at Timeout._onTimeout (D:\WEB\gbf\gbf-autopilot\server\dist\server.js:403:43)
[0]     at ontimeout (timers.js:475:11)
[0]     at tryOnTimeout (timers.js:310:5)
[0]     at Timer.listOnTimeout (timers.js:270:5)
[0] 2018-03-07T12:59:58.237Z - debug: Stopping socket 'TJQUGL_Dg6psBelWAAAA'
[0] 2018-03-07T12:59:58.235Z - info: BP berry used: 0
[1] 127.0.0.1 - - [07/Mar/2018 20:59:58] "POST / HTTP/1.1" 200 -
[0] 2018-03-07T12:59:58.252Z - info: Autopilot stopped.
```

**Comment by Frizz925** [comment]
Have you properly installed Viramate and enable its web API?

**Comment by cccwzi** [comment]
OK I will check it later. 
But it used to work fine .(I mean the old version).

**Comment by cccwzi** [comment]
Thanks. it fixed!
