### ISSUE TITLE
Next button not clicked after battle finishes

### ISSUE THREAD

**Issue by Frizz925** [Frizz925/gbf-autopilot-core#3]
Original post: https://github.com/Frizz925/gbf-autopilot/issues/15

Summary
after kill monster it can not click next button

Branch
master

Commit hash
https://github.com/Frizz925/gbf-autopilot/commit/991ab1716c5b3b76fad1ee8e1024e1f75b84f28f

System information

OS: Windows 10 Pro 64-bit
Screen resolution: 1680x1050 @ 1.0x
Chrome version: 65.0.3298.4 (Official Build) (32-bit)
Node.js version: v8.9.4
Python version: 3.6.4

Configuration
```ini
[Server]
ListenerPort=49544
ProcessTimeoutInMs=60000
WorkerTimeoutInMs=1000
WaitAjaxTimeoutInMs=5000

[Controller]
ListenerPort=49545
MouseTween=easeInOutCubic

[Debug]
LogLevel=debug
LogToFile=false
LogToOutput=true
LogToFileDirectory=log
LogSocket=false
ThrowErrors=false
TrialBattleMode=false

[General]
Language=en
MaxNumActionRetries=3
MinWaitTimeInMsAfterRefresh=2000
TimeLimitInSeconds=3600
UseViramate=true
MaxNumPotionsToUse=999
UseFullElixirsWhenNoRemainingHalfAPPotions=false
UseFullElixirsFirst=false
TreasureId=
TreasureName=
TreasureTarget=

[Inputs]
DelayInMsBetweenMouseDownAndUp=40
RandomDelayInMsBetweenMouseDownAndUp=20
MouseSpeed=580
MouseSpeedBase=150
MouseScrollSpeed=250
ExitKeyCode=112
WaitTimeInMsBeforeClickInput=50

[PartySelection]
PreferredPartyGroup=1
PreferredPartyDeck=5
PreferredPartySet=A
PreferredNightmareModePartyGroup=1
PreferredNightmareModePartyDeck=1
PreferredNightmareModePartySet=A

[Summons]
PreferredSummons=Kaguya,Rabbit
DefaultSummonAttributeTab=Mise
RerollSummonWhenNoPreferredSummonWasFound=false

[Combat]
MinWaitTimeInMsAfterAttack=500
MinWaitTimeInMsAfterSummon=3000
MinWaitTimeInMsAfterAbility=2200
LuaScript=

[PokerMode]
Enabled=false
ChipAmount=1000
WinningRoundCap=5
WinningChipsCap=16000
WinningRateBase=0.75
WinningRateModifier=0.08

[EventMode]
Enabled=true
EventRaidUrl="http://game.granbluefantasy.jp/#quest/supporter/510031/5"
EventRaidScript=
NightmareModeUrl="http://game.granbluefantasy.jp/#quest/supporter/510051/5"
NightmareModeScript=
EventPageUrl="http://game.granbluefantasy.jp/#quest/extra"
NightmareModePreferredSummons=Kaguya
NightmareModeSummonAttributeTab=Mise
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
NightmareModeAvailableAtStart=false
WaitTimeInMsAfterEventPageIsLoaded=1000

[EventTreasureMode]
Enabled=false
EventTreasureUrl=
EventTreasureSoloUrl=
EventTreasureSoloModeScript=
EventTreasureRaidUrl=
EventTreasureRaidModeScript=
EventTreasureRaidItemRequiredCount=
NightmareModeUrl=
NightmareModeScript=
NightmareModePreferredSummons=
NightmareModeSummonAttributeTab=
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
NightmareModeAvailableAtStart=false

[RiseOfTheBeastsMode]
Enabled=false
RiseOfTheBeastsUrl=
RiseOfTheBeastsLuaScript=

[CoopSoloMode]
Enabled=false
LuaScript=

[CoopGuestMode]
Enabled=false
LuaScript=

[CustomizedScheduling]
Enabled=false
SchedulingLuaScript=

[DimensionalHalo]
RetreatWhenNoDimensionalHaloTransformation=true
```

Log
```
[0] 2018-01-19T08:14:36.125Z - debug: Socket 'i-Jma3mayLwbf-wGAAAD' started
[0] extensions.js not found. Not loading extensions.
[0] 2018-01-19T08:14:36.133Z - info: Autopilot started.
[0] 2018-01-19T08:14:36.133Z - info: Using 'Event' mode.
[1] 127.0.0.1 - - [19/Jan/2018 16:14:36] "POST /start HTTP/1.1" 200 -
[0] 2018-01-19T08:14:36.134Z - debug: Location change: http://game.granbluefantasy.jp/#quest/extra
[0] 2018-01-19T08:14:37.153Z - debug: Waiting element: .atx-lead-link
[0] 2018-01-19T08:14:37.161Z - debug: Checking element: .ico-difficulty-5,.ico-difficulty-8
[0] 2018-01-19T08:14:37.192Z - info: Using quest page: http://game.granbluefantasy.jp/#quest/supporter/510031/5
[0] 2018-01-19T08:14:37.193Z - debug: Ajax: GET /quest/user_action_point
[0] 2018-01-19T08:14:37.382Z - debug: Ajax: GET /quest/quest_data/510031/5
[0] 2018-01-19T08:14:37.527Z - debug: Ajax: POST /quest/set_return_point
[0] 2018-01-19T08:14:37.723Z - debug: Location change: http://game.granbluefantasy.jp/#quest/supporter/510031/5
[0] 2018-01-19T08:14:38.809Z - debug: Waiting element: .atx-lead-link
[0] 2018-01-19T08:14:38.819Z - debug: Checking element: .icon-supporter-type-undefined.unselected
[0] 2018-01-19T08:14:38.832Z - debug: Timeout: 50
[0] 2018-01-19T08:14:38.883Z - debug: Preferred summons: 0=Kaguya, 1=Rabbit
[0] 2018-01-19T08:14:38.896Z - debug: Selected summon: Kaguya
[0] 2018-01-19T08:14:38.896Z - debug: Timeout: 50
[1] 127.0.0.1 - - [19/Jan/2018 16:14:39] "POST /click HTTP/1.1" 200 -
[0] 2018-01-19T08:14:39.443Z - debug: Waiting element: .pop-deck.supporter
[0] 2018-01-19T08:14:46.680Z - debug: Timeout: 500
[0] 2018-01-19T08:14:47.180Z - debug: Using party group: 1
[0] 2018-01-19T08:14:47.180Z - debug: Clicking with condition: .btn-select-group.id-1
[0] 2018-01-19T08:14:47.180Z - debug: Checking element: .btn-select-group.id-1.selected
[0] 2018-01-19T08:14:47.188Z - debug: Timeout: 500
[0] 2018-01-19T08:14:47.689Z - debug: Using party deck: 5
[0] 2018-01-19T08:14:47.689Z - debug: Clicking with condition: .prt-deck-slider li:nth-child(5) > a
[0] 2018-01-19T08:14:47.689Z - debug: Checking element: .prt-deck-slider li:nth-child(5) > a.flex-active
[0] 2018-01-19T08:14:47.693Z - debug: Starting battle...
[0] 2018-01-19T08:14:47.694Z - debug: Clicking with condition: .btn-usual-ok
[0] 2018-01-19T08:14:47.694Z - debug: Clicking element: .btn-usual-ok
[1] 127.0.0.1 - - [19/Jan/2018 16:14:48] "POST /click HTTP/1.1" 200 -
[0] 2018-01-19T08:14:48.224Z - debug: Timeout: 1500
[0] 2018-01-19T08:14:49.376Z - debug: Waiting element: .btn-attack-start.display-on,.btn-result,.cnt-result
[0] 2018-01-19T08:14:54.511Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:14:54.678Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:14:54.773Z - debug: Checking element: .btn-result
[0] 2018-01-19T08:14:54.813Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:14:54.852Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:14:54.880Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:14:55.034Z - info: Attacking...
[0] 2018-01-19T08:14:55.035Z - debug: Waiting for action result
[0] 2018-01-19T08:14:55.036Z - debug: Clicking with condition: .btn-attack-start.display-on
[0] 2018-01-19T08:14:55.036Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:14:55.082Z - debug: Clicking element: .btn-attack-start.display-on
[1] 127.0.0.1 - - [19/Jan/2018 16:14:55] "POST /click HTTP/1.1" 200 -
[0] 2018-01-19T08:14:55.807Z - debug: Timeout: 1500
[0] 2018-01-19T08:14:56.283Z - debug: Action result received
[0] 2018-01-19T08:14:56.283Z - debug: Timeout: 500
[0] 2018-01-19T08:14:56.822Z - debug: Waiting element: .btn-attack-start.display-on,.btn-result,.cnt-result
[0] 2018-01-19T08:14:57.308Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:15:00.301Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:15:00.384Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:15:00.467Z - debug: Checking element: .btn-result
[0] 2018-01-19T08:15:00.512Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:15:00.531Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:15:00.551Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:15:00.628Z - info: Attacking...
[0] 2018-01-19T08:15:00.628Z - debug: Waiting for action result
[0] 2018-01-19T08:15:00.628Z - debug: Clicking with condition: .btn-attack-start.display-on
[0] 2018-01-19T08:15:00.628Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:15:00.648Z - debug: Clicking element: .btn-attack-start.display-on
[1] 127.0.0.1 - - [19/Jan/2018 16:15:01] "POST /click HTTP/1.1" 200 -
[0] 2018-01-19T08:15:01.239Z - debug: Timeout: 1500
[0] 2018-01-19T08:15:01.564Z - debug: Action result received
[0] 2018-01-19T08:15:01.564Z - debug: Timeout: 500
[0] 2018-01-19T08:15:02.087Z - debug: Waiting element: .btn-attack-start.display-on,.btn-result,.cnt-result
[0] 2018-01-19T08:15:02.741Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:15:03.239Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:15:03.309Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:15:03.387Z - debug: Checking element: .btn-result
[0] 2018-01-19T08:15:03.401Z - debug: Timeout: 1500
[0] 2018-01-19T08:15:04.901Z - debug: Waiting element: .cnt-result
[0] 2018-01-19T08:16:04.903Z - info: AP potion used: 0
[0] 2018-01-19T08:16:04.903Z - error: Error: Action element({"selector":".cnt-result","scroll":false,"retry":true}) timed out after 60000ms!
[0] at Timeout._onTimeout (D:\game\gbf\gbfbackup\gbf-autopilot\server\dist\server.js:319:43)
[0] at ontimeout (timers.js:475:11)
[0] at tryOnTimeout (timers.js:310:5)
[0] at Timer.listOnTimeout (timers.js:270:5)
[0] 2018-01-19T08:16:04.903Z - debug: Stopping socket 'i-Jma3mayLwbf-wGAAAD'
[1] 127.0.0.1 - - [19/Jan/2018 16:16:04] "POST /stop HTTP/1.1" 200 -
[0] 2018-01-19T08:16:04.910Z - info: Autopilot stopped.
```

**Comment by Frizz925** [comment]
This seems like a bug that occurs randomly. The fix is going to take some time.

**Comment by srwgin** [comment]
I see you commit Fixed error during checking next button
then update try it again
can not click now

log
[0] 2018-01-23T07:02:57.835Z - debug: Checking element: .btn-result
[0] 2018-01-23T07:02:57.851Z - debug: Timeout: 1500
[0] 2018-01-23T07:02:59.353Z - debug: Waiting element: .cnt-result
[0] 2018-01-23T07:03:59.357Z - info: AP potion used: 0
[0] 2018-01-23T07:03:59.358Z - error:  Error: Action element({"selector":".cnt-result","scroll":false,"retry":true}) timed out after 60000ms!
[0]     at Timeout._onTimeout (D:\game\gbf\gbfbackup\gbf-autopilot\server\dist\server.js:319:43)
[0]     at ontimeout (timers.js:475:11)
[0]     at tryOnTimeout (timers.js:310:5)
[0]     at Timer.listOnTimeout (timers.js:270:5)
[0] 2018-01-23T07:03:59.359Z - debug: Stopping socket 'AMG7zphCqHe_juNWAAAA'
[1] 127.0.0.1 - - [23/Jan/2018 15:03:59] "POST /stop HTTP/1.1" 200 -
[0] 2018-01-23T07:03:59.368Z - info: Autopilot stopped.

**Comment by Frizz925** [comment]
Can you post the full log from when the bot starts the battle?

**Comment by srwgin** [comment]
D:\game\gbf\gbfbackup\gbf-autopilot>npm start

> gbf-autopilot@0.0.1 start D:\game\gbf\gbfbackup\gbf-autopilot
> cross-env NODE_ENV=production concurrently "node index.js" "python controller.py"
[1]  * Running on http://localhost:49545/ (Press CTRL+C to quit)
[0] 2018-01-23T07:58:51.434Z - debug: Started listening on localhost:49544
[0] 2018-01-23T07:58:55.764Z - debug: Client 'C9tIeGkUmhppECczAAAA' connected!
[0] 2018-01-23T07:59:22.965Z - debug: Socket 'C9tIeGkUmhppECczAAAA' started
[1] 127.0.0.1 - - [23/Jan/2018 15:59:22] "POST /start HTTP/1.1" 200 -
[0] 2018-01-23T07:59:22.996Z - info: Autopilot started.
[0] 2018-01-23T07:59:23.001Z - info: Using 'Event' mode.
[0] 2018-01-23T07:59:23.030Z - debug: Location change: http://game.granbluefantasy.jp/#quest/extra
[0] 2018-01-23T07:59:24.050Z - debug: Waiting element: .atx-lead-link
[0] 2018-01-23T07:59:24.090Z - debug: Checking element: .ico-difficulty-5,.ico-difficulty-8
[0] 2018-01-23T07:59:24.315Z - info: Using quest page: http://game.granbluefantasy.jp/#quest/supporter/510031/5
[0] 2018-01-23T07:59:24.328Z - debug: Ajax: GET /quest/user_action_point
[0] 2018-01-23T07:59:24.468Z - debug: Ajax: GET /quest/quest_data/510031/5
[0] 2018-01-23T07:59:24.619Z - debug: Ajax: POST /quest/set_return_point
[0] 2018-01-23T07:59:24.792Z - debug: Location change: http://game.granbluefantasy.jp/#quest/supporter/510031/5
[0] 2018-01-23T07:59:25.833Z - debug: Waiting element: .atx-lead-link
[0] 2018-01-23T07:59:25.838Z - debug: Checking element: .icon-supporter-type-7.unselected
[0] 2018-01-23T07:59:25.843Z - debug: Clicking element: .icon-supporter-type-7
[1] 127.0.0.1 - - [23/Jan/2018 15:59:26] "POST /click HTTP/1.1" 200 -
[0] 2018-01-23T07:59:26.352Z - debug: Timeout: 50
[0] 2018-01-23T07:59:26.403Z - debug: Preferred summons: 0=カグヤ, 1=ホワイトラビット, 2=ブラックラビット
[0] 2018-01-23T07:59:26.420Z - info: Selected summon: カグヤ
[0] 2018-01-23T07:59:26.420Z - debug: Timeout: 50
[1] 127.0.0.1 - - [23/Jan/2018 15:59:26] "POST /click HTTP/1.1" 200 -
[0] 2018-01-23T07:59:26.971Z - debug: Waiting element: .pop-deck.supporter
[0] 2018-01-23T07:59:27.327Z - debug: Timeout: 500
[0] 2018-01-23T07:59:27.828Z - debug: Using party set: A
[0] 2018-01-23T07:59:27.829Z - debug: Clicking with condition: .btn-deck-group
[0] 2018-01-23T07:59:27.829Z - debug: Checking element: .btn-deck-group.type-groupA
[0] 2018-01-23T07:59:27.836Z - debug: Using party group: 1
[0] 2018-01-23T07:59:27.836Z - debug: Clicking with condition: .btn-select-group.id-1
[0] 2018-01-23T07:59:27.836Z - debug: Checking element: .btn-select-group.id-1.selected
[0] 2018-01-23T07:59:27.843Z - debug: Timeout: 500
[0] 2018-01-23T07:59:28.344Z - debug: Using party deck: 5
[0] 2018-01-23T07:59:28.345Z - debug: Clicking with condition: .prt-deck-slider li:nth-child(5) > a
[0] 2018-01-23T07:59:28.345Z - debug: Checking element: .prt-deck-slider li:nth-child(5) > a.flex-active
[0] 2018-01-23T07:59:28.357Z - debug: Clicking element: .prt-deck-slider li:nth-child(5) > a
[1] 127.0.0.1 - - [23/Jan/2018 15:59:28] "POST /click HTTP/1.1" 200 -
[0] 2018-01-23T07:59:28.866Z - debug: Timeout: 750
[0] 2018-01-23T07:59:29.618Z - debug: Checking element: .prt-deck-slider li:nth-child(5) > a.flex-active
[0] 2018-01-23T07:59:29.624Z - debug: Starting battle...
[0] 2018-01-23T07:59:29.625Z - debug: Clicking with condition: .btn-usual-ok
[0] 2018-01-23T07:59:29.625Z - debug: Clicking element: .btn-usual-ok
[1] 127.0.0.1 - - [23/Jan/2018 15:59:30] "POST /click HTTP/1.1" 200 -
[0] 2018-01-23T07:59:30.135Z - debug: Timeout: 750
[0] 2018-01-23T07:59:30.885Z - debug: Clicking element: .btn-usual-ok
[0] 2018-01-23T07:59:31.265Z - debug: Waiting element: .btn-attack-start.display-on,.btn-result,.cnt-result
[1] 127.0.0.1 - - [23/Jan/2018 15:59:31] "POST /click HTTP/1.1" 200 -
[0] 2018-01-23T07:59:31.519Z - debug: Timeout: 750
[0] 2018-01-23T07:59:37.633Z - debug: Viramate: type=getCombatState
[0] 2018-01-23T07:59:37.766Z - debug: Viramate: type=getCombatState
[0] 2018-01-23T07:59:37.939Z - debug: Checking element: .btn-result
[0] 2018-01-23T07:59:37.988Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-23T07:59:38.148Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-23T07:59:38.168Z - debug: Viramate: type=getCombatState
[0] 2018-01-23T07:59:38.365Z - info: Attacking...
[0] 2018-01-23T07:59:38.367Z - debug: Waiting for action result
[0] 2018-01-23T07:59:38.368Z - debug: Clicking with condition: .btn-attack-start.display-on
[0] 2018-01-23T07:59:38.368Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-23T07:59:38.384Z - debug: Clicking element: .btn-attack-start.display-on
[1] 127.0.0.1 - - [23/Jan/2018 15:59:39] "POST /click HTTP/1.1" 200 -
[0] 2018-01-23T07:59:39.077Z - debug: Timeout: 750
[0] 2018-01-23T07:59:39.488Z - debug: Action result received
[0] 2018-01-23T07:59:39.489Z - debug: Timeout: 500
[0] 2018-01-23T07:59:39.828Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-23T07:59:40.002Z - debug: Waiting element: .btn-attack-start.display-on,.btn-result,.cnt-result
[0] 2018-01-23T07:59:42.817Z - debug: Viramate: type=getCombatState
[0] 2018-01-23T07:59:42.935Z - debug: Viramate: type=getCombatState
[0] 2018-01-23T07:59:43.129Z - debug: Checking element: .btn-result
[0] 2018-01-23T07:59:43.171Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-23T07:59:43.193Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-23T07:59:43.214Z - debug: Viramate: type=getCombatState
[0] 2018-01-23T07:59:43.329Z - info: Attacking...
[0] 2018-01-23T07:59:43.330Z - debug: Waiting for action result
[0] 2018-01-23T07:59:43.330Z - debug: Clicking with condition: .btn-attack-start.display-on
[0] 2018-01-23T07:59:43.330Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-23T07:59:43.357Z - debug: Clicking element: .btn-attack-start.display-on
[1] 127.0.0.1 - - [23/Jan/2018 15:59:43] "POST /click HTTP/1.1" 200 -
[0] 2018-01-23T07:59:43.886Z - debug: Timeout: 750
[0] 2018-01-23T07:59:44.264Z - debug: Action result received
[0] 2018-01-23T07:59:44.264Z - debug: Timeout: 500
[0] 2018-01-23T07:59:44.638Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-23T07:59:44.796Z - debug: Waiting element: .btn-attack-start.display-on,.btn-result,.cnt-result
[0] 2018-01-23T07:59:45.618Z - debug: Viramate: type=getCombatState
[0] 2018-01-23T07:59:45.710Z - debug: Viramate: type=getCombatState
[0] 2018-01-23T07:59:45.809Z - debug: Checking element: .btn-result
[0] 2018-01-23T07:59:45.822Z - debug: Timeout: 1500
[0] 2018-01-23T07:59:47.324Z - debug: Waiting element: .cnt-result
[0] 2018-01-23T08:00:47.329Z - info: AP potion used: 0
[0] 2018-01-23T08:00:47.330Z - error:  Error: Action element({"selector":".cnt-result","scroll":false,"retry":true}) timed out after 60000ms!
[0]     at Timeout._onTimeout (D:\game\gbf\gbfbackup\gbf-autopilot\server\dist\server.js:319:43)
[0]     at ontimeout (timers.js:475:11)
[0]     at tryOnTimeout (timers.js:310:5)
[0]     at Timer.listOnTimeout (timers.js:270:5)
[0] 2018-01-23T08:00:47.331Z - debug: Stopping socket 'C9tIeGkUmhppECczAAAA'
[1] 127.0.0.1 - - [23/Jan/2018 16:00:47] "POST /stop HTTP/1.1" 200 -
[0] 2018-01-23T08:00:47.338Z - info: Autopilot stopped.

**Comment by Frizz925** [comment]
You're probably using commit earlier than https://github.com/Frizz925/gbf-autopilot-core/commit/6600739969cceb044bec55f5469a770d477b9422 with Viramate web API disabled.

**Comment by Frizz925** [comment]
Closing this since the bug has not occurred for a long while.
