### ISSUE TITLE
Cannot run lua script

### ISSUE THREAD

**Issue by serenotus** [Frizz925/gbf-autopilot-core#9]
### Summary
Sorry about here's an error occured again in a short time.

According to [Issue#7](https://github.com/Frizz925/gbf-autopilot-core/issues/7) has been solved.
I update and rebuild the core extension, then it becomes unable to use script state.
Looks like it's not autopilot's problem, fengari lib's.

In my case, it failed in schedule mode but run successfully in event mode without script.
The schedule mode could be used before I update it.

Thank you for your helping.

### Branch
master

### Commit hash
https://github.com/Frizz925/gbf-autopilot/commit/ac8c79c6b854bf807f5145ebfd44627df91454e0
&
https://github.com/Frizz925/gbf-autopilot-core/commit/1620e2e3789420a5d7aa7e667c36712eaedc81c5

### Game information
Account type: Mobage
Ingame language: Japanese

### System information
OS: Windows 10 Pro 32-bit
Screen resolution: 1745x843 @ 1.0x
Chrome version: 63.0.3239.132 (Official Build) (32-bit)
Node.js version: v9.4.0
Python version: 3.6.4

### Configuration
```
[Server]
ListenerPort=49544
ProcessTimeoutInMs=60000
WorkerTimeoutInMs=500
WaitAjaxTimeoutInMs=5000
JsonRpcEndpoint=/jsonrpc

[Controller]
ListenerPort=49545
MouseTween=easeInOutCubic

[Debug]
LogLevel=debug
LogToFile=false
LogToOutput=true
LogToFileDirectory=log
LogSocket=false
ThrowErrors=false
TrialBattleMode=false

[General]
Language=jp
MaxNumActionRetries=2
MinWaitTimeInMsAfterRefresh=2000
TimeLimitInSeconds=3600
UseViramate=true
MaxNumPotionsToUse=15
UseFullElixirsWhenNoRemainingHalfAPPotions=false
UseFullElixirsFirst=false
Treasure=
TreasureTarget=

[Inputs]
DelayInMsBetweenMouseDownAndUp=40
RandomDelayInMsBetweenMouseDownAndUp=20
MouseSpeed=580
MouseSpeedBase=150
MouseScrollSpeed=250
ExitKeyCode=113
WaitTimeInMsBeforeClickInput=50

[PartySelection]
PreferredPartyGroup=3
PreferredPartyDeck=2
PreferredPartySet=A
PreferredNightmareModePartyGroup=6
PreferredNightmareModePartyDeck=1
PreferredNightmareModePartySet=A

[Summons]
OnlyRerollSummonsEnabled=false
PreferredSummons=シヴァ
DefaultSummonAttributeTab=火
RerollSummonWhenNoPreferredSummonWasFound=true

[Combat]
MinWaitTimeInMsAfterAttack=500
MinWaitTimeInMsAfterSummon=3000
MinWaitTimeInMsAfterAbility=1000
LuaScript=

[PokerMode]
Enabled=false
ChipAmount=1000
WinningRoundCap=5
WinningChipsCap=16000
WinningRateBase=0.75
WinningRateModifier=0.08

[EventMode]
Enabled=true
EventRaidUrl="http://game.granbluefantasy.jp/#quest/supporter/510031/5"
EventRaidScript=
NightmareModeUrl=
NightmareModeScript=
EventPageUrl="http://game.granbluefantasy.jp/#quest/extra"
NightmareModePreferredSummons=シヴァ
NightmareModeSummonAttributeTab=火
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
NightmareModeAvailableAtStart=false
WaitTimeInMsAfterEventPageIsLoaded=1000

[EventTreasureMode]
Enabled=false
EventTreasureUrl="http://game.granbluefantasy.jp/#event/treasureraid064"
EventTreasureSoloUrl="http://game.granbluefantasy.jp/#quest/supporter/725391/1"
EventTreasureSoloModeScript=scripts/tester/event_extreme_by_test_fire.lua
EventTreasureRaidUrl="http://game.granbluefantasy.jp/#quest/supporter/725401/1/0/10258"
EventTreasureRaidModeScript=scripts/tester/event_extreme_by_test_fire.lua
EventTreasureRaidItemRequiredCount=3
NightmareModeUrl=
NightmareModeScript=
NightmareModePreferredSummons=
NightmareModeSummonAttributeTab=
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
NightmareModeAvailableAtStart=false

[RiseOfTheBeastsMode]
Enabled=false
RiseOfTheBeastsUrl=
RiseOfTheBeastsLuaScript=

[CoopSoloMode]
Enabled=false
LuaScript=

[CoopGuestMode]
Enabled=false
LuaScript=

[CustomizedScheduling]
Enabled=false
SchedulingLuaScript=scripts/tester/my_daily_scheduling.lua

[DimensionalHalo]
RetreatWhenNoDimensionalHaloTransformation=true
```

### Log
```
$ npm start

> gbf-autopilot@0.0.1 start C:\git_repository\gbf-autopilot
> cross-env NODE_ENV=production concurrently "node index.js" "python server.py"

[0] extensions.js not found. Not loading extensions.
[1]  * Running on http://localhost:49545/ (Press CTRL+C to quit)
[0] 2018-02-01T02:43:01.908Z - debug: Started listening on localhost:49544
[0] 2018-02-01T02:43:38.667Z - debug: Client 'cWh0LvF6mvi91h1BAAAA' connected!
[0] 2018-02-01T02:43:46.628Z - debug: Socket 'cWh0LvF6mvi91h1BAAAA' started
[0] extensions.js not found. Not loading extensions.
[1] 127.0.0.1 - - [01/Feb/2018 10:43:46] "POST / HTTP/1.1" 200 -
[0] 2018-02-01T02:43:46.653Z - info: Autopilot started.
[0] 2018-02-01T02:43:46.655Z - info: Using 'Scheduling' mode.
[0] 2018-02-01T02:43:46.825Z - info: AP potion used: 0
[0] 2018-02-01T02:43:46.826Z - error:  TypeError: _fengari.lua.to_luastring is not a function
[0]     at Script (C:\git_repository\gbf-autopilot\node_modules\gbf-autopilot-core\build\server\steps\Battle\Script\index.js:17:54)
[0]     at Worker.Script (C:\git_repository\gbf-autopilot\node_modules\gbf-autopilot-core\build\server\steps\Step2.js:10:21)
[0]     at C:\git_repository\gbf-autopilot\node_modules\gbf-autopilot-core\build\server\steps\Step.js:20:29
[0]     at new Promise (<anonymous>)
[0]     at Worker.Battle.Script (C:\git_repository\gbf-autopilot\node_modules\gbf-autopilot-core\build\server\steps\Step.js:19:12)
[0]     at C:\git_repository\gbf-autopilot\server\dist\server\Worker.js:42:27
[0]     at Promise._execute (C:\git_repository\gbf-autopilot\node_modules\bluebird\js\release\debuggability.js:303:9)
[0]     at Promise._resolveFromExecutor (C:\git_repository\gbf-autopilot\node_modules\bluebird\js\release\promise.js:483:18)
[0]     at new Promise (C:\git_repository\gbf-autopilot\node_modules\bluebird\js\release\promise.js:79:10)
[0]     at Worker.run (C:\git_repository\gbf-autopilot\server\dist\server\Worker.js:27:14)
[0]     at C:\git_repository\gbf-autopilot\server\dist\server\WorkerManager.js:121:30
[0]     at Promise._execute (C:\git_repository\gbf-autopilot\node_modules\bluebird\js\release\debuggability.js:303:9)
[0]     at Promise._resolveFromExecutor (C:\git_repository\gbf-autopilot\node_modules\bluebird\js\release\promise.js:483:18)
[0]     at new Promise (C:\git_repository\gbf-autopilot\node_modules\bluebird\js\release\promise.js:79:10)
[0]     at WorkerManager.run (C:\git_repository\gbf-autopilot\server\dist\server\WorkerManager.js:113:14)
[0]     at C:\git_repository\gbf-autopilot\server\dist\server\WorkerManager.js:105:16
[0] 2018-02-01T02:43:46.826Z - debug: Stopping socket 'cWh0LvF6mvi91h1BAAAA'
[1] 127.0.0.1 - - [01/Feb/2018 10:43:46] "POST / HTTP/1.1" 200 -
[0] 2018-02-01T02:43:46.834Z - info: Autopilot stopped.
```

**Comment by Frizz925** [comment]
Yeah this is caused by fengari's breaking change where they moved the *to_luastring* API out of the *lua* namespace (https://github.com/fengari-lua/fengari/issues/105, https://github.com/fengari-lua/fengari/commit/a39f24f204a15cb4587e75b38424952fe444d9d2#diff-b0dee7c76cad7a72c292fa299946f0c7). I'll push a hotfix sometime later today.

If you feel like fixing it yourself, you can browse to https://github.com/Frizz925/gbf-autopilot-core/tree/master/src/server/steps/Battle/Script for a start.

**Comment by serenotus** [comment]
I use the previous fengari's file to overwrite it, then everything is good right now.
Thank god that I didn't remove those completely yet.
<img width="72" alt="temp" src="https://user-images.githubusercontent.com/27949015/35676908-8e2fa258-0788-11e8-9cd0-c3272ece9899.PNG">

**Comment by Frizz925** [comment]
Yeah I should add the commit hash into the package.json for now.

**Comment by Frizz925** [comment]
Decided to use older Fengari commits to avoid the breaking changes (https://github.com/Frizz925/gbf-autopilot-core/blob/f3493c1462a73ffde7967d9f1c5fd0b224fd8fd2/package.json#L32-L33). Should work now.

**Comment by serenotus** [comment]
Yeah, I restart autopilot from `git clone` just now, It's great successful.
And I saw you choose the commits which is over 3 weeks ago, this is somewhat higher than what I thought.
At the end, thank you for helping me to use autopilot.
